### ISSUE TITLE
Problem scrape XML

### ISSUE THREAD

**Issue by swekim** [darrylwhitmore/NScrape#1]
I fixed the problem, by changed line 438 in WebClient.cs

To this:
else if (contentType.StartsWith("text/xml", StringComparison.OrdinalIgnoreCase) || contentType.StartsWith("application/xml", StringComparison.OrdinalIgnoreCase))

**Comment by darrylwhitmore** [comment]
Thanks for the fix, and sorry for the delay in responding. Would you like to submit a pull request, or shall I just make the change?

**Comment by qmfrederik** [comment]
Pull request #6 should fix this.

**Comment by darrylwhitmore** [comment]
Resolved by pull request #6.
