### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by qmfrederik** [darrylwhitmore/NScrape#23]
Gentle ping ;-)

**Comment by darrylwhitmore** [comment]
Apologies, you're remarkably patient! :)

**Comment by darrylwhitmore** [comment]
Release 0.4.0 is finally out at [https://www.nuget.org/packages/NScrape/0.4.0](https://www.nuget.org/packages/NScrape/0.4.0).

**Comment by qmfrederik** [comment]
Thanks!
