### ISSUE TITLE
Quastion

### ISSUE THREAD

**Issue by Yevheniia-hub** [darrylwhitmore/NScrape#26]
Tell, me please, where did you find class- myforecast-current-lrg?
Sorry, I don't understand.

**Comment by darrylwhitmore** [comment]
In the tutorial, after you submit the form to get the information for Fairbanks, Alaska, the HTML that is returned contains the data you want to scrape out. You just have to identify some way to uniquely locate that data within the HTML. For the tutorial, I used a couple of class attribute tags that I found to be reliable ways to pinpoint the conditions ("myforecast-current") and temperature ("myforecast-current-lrg"). In the scraper class, I used HTML Agility Pack to pull out these attributes and get their values, which is the data was after.

Below is the HTML that the form submission returns (both in raw HTML form and as seen in Chrome's Developer Tools), with the class attributes marked. I'll also update the tutorial to include these images to help others with the same question! 

(When I saw this question I was afraid the underlying website had been updated, causing my tutorial code to break. Hat tip to the US National Weather Service for not changing their site after all these years!)

### Raw HTML
![Fairbanks Alaska weather result](https://user-images.githubusercontent.com/1014874/101415271-3b47f000-38ad-11eb-8a1c-abcaceb302e8.jpg)

### Chrome Developer Tools
![Fairbanks Alaska weather developer tools result](https://user-images.githubusercontent.com/1014874/101416615-d80b8d00-38af-11eb-961e-1312793e67ed.jpg)

**Comment by Yevheniia-hub** [comment]
Thank you so much :)
