### ISSUE TITLE
A plug in model for content types

### ISSUE THREAD

**Issue by qmfrederik** [darrylwhitmore/NScrape#3]
Hi,

NScrape is great - it's the first library I know of that kind of provides an equivalent of mechanize for .NET.

That said, I think one of the limitations is that the content types are currently hard coded. For example, I've encountered an issue with support for JSON, while somebody else had an issue with support for the application/xml content type.

Right now, if a content type is not supported, you get an `UnsupportedWebResponse` which leaves you without the ability to actually get the data that was returned, even if you would be able to properly parse the data that was returned.

I guess any of the following three options could already alleviate the pain:
1. Have the `UnsupportedWebResponse` expose the binary data that was returned by the server
2. Allow the user to add additional content types that would either be treated as a `TextWebResponse` or some kind of `BinaryWebResponse`
3. Provide an extensibility model that allows users to register new content types and the corresponding `WebResponse` class. For example, something like a `Dictionary<string, Func<HttpWebResponse, WebResponse>>`

Cheers,

Frederik.

**Comment by darrylwhitmore** [comment]
Hi Frederik, thanks and excellent suggestion. I've been a little short of time lately, but I'll work on this. In the meantime, your pull request should ease the pain in the short term; I'll get it taken care of next chance I get. Thanks so much for contributing!

**Comment by qmfrederik** [comment]
Hi Darryl,

Sounds good. I'm actually using NScrape in one of my project and came up with a couple of issues. I've fixed them and create pull requests for each fix. 

I tried to keep the pull requests clean, let me know if you have questions.

Frederik.

**Comment by darrylwhitmore** [comment]
Hi Frederik, I see you have been busy! Originally NScrape was just something for myself, so the functionality was limited to just my immediate needs. Your ideas are all great and really help make it a more general purpose framework. Thanks again for all the help! Bear with me, any delay in processing your contributions is only due to my limited time, not disinterest.

**Comment by darrylwhitmore** [comment]
Resolved by pull request #8
